replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

page:
  title: "Web App"
  environment: ""
  message: "Hello World"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi

podAnnotations: {}